### PR TITLE
Internal: Faster reduce iteration

### PR DESCRIPTION
**Pull request by ryan-roemer**
- Applies @gabmontes changes in #121 to a new internal branch. Closes #121 
- Applies the changes to similar inefficient patterns.
- Finally got CI sorted out... 👿 

@gabmontes -- If you have a moment, can you pull this branch and let me know how it works for you? Thanks!

### CODE REVIEW

**Comment by gabmontes** [comment]
@ryan-roemer I tested this branch packaging my service and works pretty fast! Packaging speed is awesome now!

By the way, in my original PR #121 I replaced the `reduce` with a plain `forEach` as that was even 10% faster.

Thanks again!

**Comment by ryan-roemer** [comment]
@gabmontes -- Thanks for kicking the tires!

> I replaced the reduce with a plain forEach as that was even 10% faster.

That's really interesting! They're really the equivalent (outside scope variable vs. passed-as-param variable). So for like a 20K file bundle you're seeing how many secs difference with just `reduce` vs `forEach`?

Separate question outside the scope of this PR -- are you using tracing mode? I only ask because that sounds huge and for all the apps we've switched from "legacy/dependency mode" to trace mode have usually less than 10K files, even for enormous apps...

**Comment by gabmontes** [comment]
@ryan-roemer the two are equivalent but the reality is V8 seems to handle much better a simple `forEach` than a `reduce`. I guess this is because `forEach` is simpler i.e. less arguments to handle on each iteration.

In my service the original bundling time was ~300s. With this PR it is ~20s and with `forEach` it goes down to 15s.

And no, don't use `tracing` yet as there are some dynamic `require` that need to take care of first. Anyway the idea is to do that as this is much more efficient!

**Comment by ryan-roemer** [comment]
@gabmontes -- OK, I've switched the main reduce at issue to forEach and a couple others. Mind doing one last test to see if the results are now in line with your expectations?

If you're hitting stumbling blocks with trace mode over dynamic import misses, feel free to open an issue with the ones at issue (if they're OSS) or DM me on twitter: https://twitter.com/ryan_roemer if you want a bit more privacy and I can maybe help you work through them. We've now done a number of projects and encountered a lot of "likely appropriate resolutions" for a lot of npm packages that do weird dynamic stuff 😄

**Comment by gabmontes** [comment]
@ryan-roemer additional 10% increase in speed packaging my service! Great!!!

**Comment by ryan-roemer** [comment]
Released in `serverless-jetpack@0.10.7`

Thanks for all the help @gabmontes !

**Pull request merged**
